
# SignalCraft Light-Lab Configuration

# Colors
COLOR_PRIMARY = "#00BFFF"
COLOR_ACCENT_CYAN = "#00FFFF"
COLOR_ANOMALY_RED = "#E57373"
COLOR_BACKGROUND_DARK = "#0B141D"
COLOR_APP_DARK = "#0E1117"
COLOR_PANEL_DARK = "#161b22"

# Defaults
DEFAULT_SAMPLE_RATE = 44100
DEFAULT_TARGET_FREQ = 60.0  # Hz
DEFAULT_BANDWIDTH = 1.0     # Hz
DEFAULT_OTSU_MULTIPLIER = 1.0
DEFAULT_WINDOW_SIZE_SEC = 0.5 # Window size for analysis in seconds

# Memory Safety
MAX_FILE_SIZE_MB = 200
